nginx:
    Nginx Server:
        key: nginx
        fields:
            enabled:
                type: switch
                description: Defines whether Nginx should be activated on provision or disabled.

mysql:
    MySQL Server:
        key: mysql
        fields:
            enabled:
                type: switch
                description: Defines whether MySQL should be activated on provision or disabled.
            password:
                type: text
                description: The password for root user.
            general_log:
                type: checkbox
                description: Whether the general query log is enabled.
            slow_query_log:
                type: checkbox
                description: Whether the slow query log is enabled.
            log_queries_not_using_indexes:
                type: checkbox
                description: Whether queries that do not use indexes are logged to the slow query log.
            long_query_time:
                type: text
                description: If a query takes longer than this many seconds, then server writes the query to the slow query log file.
    phpMyAdmin:
        key: phpMyAdmin
        fields:
            enabled:
                type: switch
                description: Defines whether phpMyAdmin should be activated on provision or disabled.
            maxDbList:
                type: text
                description: The maximum number of database names to be displayed in the main panel&apos;s database list.
            maxTableList:
                type: text
                description: The maximum number of table names to be displayed in the main panel&apos;s list.
            showSQL:
                type: checkbox
                description: Defines whether SQL queries generated by phpMyAdmin should be displayed or not.
            retainQueryBox:
                type: checkbox
                description: Defines whether the SQL query box should be kept displayed after its submission.
            allowUserDropDatabase:
                type: checkbox
                description: Defines whether normal users (non-administrator) are allowed to delete their own database or not.
            confirm:
                type: checkbox
                description: Whether a warning (&quot;Are your really sure...&quot;) should be displayed when you&apos;re about to lose data.
            useDbSearch:
                type: checkbox
                description: Define whether the &quot;search string inside database&quot; is enabled or not.
            ignoreMultiSubmitErrors:
                type: checkbox
                description: Define whether phpMyAdmin will continue executing a multi-query statement if one of the queries fails. Default is to abort execution.

postgres:
    PostgreSQL Server:
        key: postgres
        fields:
            enabled:
                type: switch
                description: Defines whether PostgreSQL should be activated on provision or disabled.
            password:
                type: text
                description: The password for postgres user.
            log_min_duration_statement:
                type: text
                description: If a query takes longer than this many milliseconds, then server writes the query to the slow query log file.
    phpPgAdmin:
        key: phpPgAdmin
        fields:
            enabled:
                type: switch
                description: Defines whether phpPgAdmin should be activated on provision or disabled.

mongodb:
    MongoDB Server:
        key: mongodb
        fields:
            enabled:
                type: switch
                description: Defines whether MongoDB should be activated on provision or disabled.

redis:
    Redis Server:
        key: redis
        fields:
            enabled:
                type: switch
                description: Defines whether Redis should be activated on provision or disabled.

memcached:
    Memcached Server:
        key: memcached
        fields:
            enabled:
                type: switch
                description: Defines whether Memcache should be activated on provision or disabled.
            max_memory:
                type: input
                label: Max memory
                description: How much RAM memory to use for item storage (in megabytes).
            tcp_port:
                type: input
                label: TCP port
                description: The port to listen on for TCP connections.
    phpMemcacheAdmin:
        key: phpMemcacheAdmin
        fields:
            enabled:
                type: switch
                description: Defines whether phpMemcacheAdmin should be activated on provision or disabled.

gearman:
    Gearman Server:
        key: gearman
        fields:
            enabled:
                type: switch
                description: Defines whether Gearman should be activated on provision or disabled.

rabbitmq:
    RabbitMQ Server:
        key: rabbitmq
        fields:
            enabled:
                type: switch
                description: Defines whether RabbitMQ should be activated on provision or disabled.

elasticsearch:
    Elasticsearch Server:
        key: elasticsearch
        fields:
            enabled:
                type: switch
                description: Defines whether Elasticsearch should be activated on provision or disabled.

sphinx:
    Sphinx Server:
        key: sphinx
        fields:
            enabled:
                type: switch
                description: Defines whether Sphinx should be activated on provision or disabled.
